const tiles = {
  0: {
    name: 'grass',
    sprite: 'grass',
    mainType: 'Grass',
    type: ['grass'],
    walkable: true,
    movementPenalty: 11,
    speedBonus: 0,
    length: 4,
    sequence: false,
    rotate: [0, 90, 180, -90],
    flip: ['', 'v', 'h', 'vh']
  },
  1: {
    name: 'grassPlain',
    sprite: 'grass_plain',
    mainType: 'Grass',
    type: ['grass'],
    walkable: true,
    movementPenalty: 11,
    speedBonus: 0,
    length: 1,
    sequence: false,
  },
  2: {
    name: 'grassDirt',
    sprite: 'grass_dirt',
    mainType: 'Grass',
    type: ['grass-dirt'],
    walkable: true,
    movementPenalty: 11,
    speedBonus: 0,
    length: 8,
    sequence: true,
    rotate: [0, 90, 180, -90],
    flip: ['', 'v', 'h', 'vh']
  },
  3: {
    name: 'grassRoadCornerBR',
    sprite: 'grass_road_corner',
    mainType: 'Grass',
    type: ['grass-road'],
    walkable: true,
    movementPenalty: 0,
    speedBonus: 0.5,
    length: 4,
    sequence: false,
  },
  4: {
    name: 'grassRoadCornerBL',
    sprite: 'grass_road_corner',
    mainType: 'Grass',
    type: ['grass-road'],
    walkable: true,
    movementPenalty: 0,
    speedBonus: 0.5,
    length: 4,
    sequence: false,
    rotate: [90],
  },
  5: {
    name: 'grassRoadCornerTL',
    sprite: 'grass_road_corner',
    mainType: 'Grass',
    type: ['grass-road'],
    walkable: true,
    movementPenalty: 0,
    speedBonus: 0.5,
    length: 4,
    sequence: false,
    rotate: [180],
  },
  6: {
    name: 'grassRoadCornerTR',
    sprite: 'grass_road_corner',
    mainType: 'Grass',
    type: ['grass-road'],
    walkable: true,
    movementPenalty: 0,
    speedBonus: 0.5,
    length: 4,
    sequence: false,
    rotate: [-90],
  },
  7: {
    name: 'grassRoadTT',
    sprite: 'grass_road_t',
    mainType: 'Grass',
    type: ['grass-road'],
    walkable: true,
    movementPenalty: 0,
    speedBonus: 0.5,
    length: 4,
    sequence: false,
    flip: ['', 'h']
  },
  8: {
    name: 'grassRoadTR',
    sprite: 'grass_road_t',
    mainType: 'Grass',
    type: ['grass-road'],
    walkable: true,
    movementPenalty: 0,
    speedBonus: 0.5,
    length: 4,
    sequence: false,
    rotate: [90],
    flip: ['', 'v']
  },
  9: {
    name: 'grassRoadTB',
    sprite: 'grass_road_t',
    mainType: 'Grass',
    type: ['grass-road'],
    walkable: true,
    movementPenalty: 0,
    speedBonus: 0.5,
    length: 4,
    sequence: false,
    rotate: [180],
    flip: ['', 'h']
  },
  10: {
    name: 'grassRoadTL',
    sprite: 'grass_road_t',
    mainType: 'Grass',
    type: ['grass-road'],
    walkable: true,
    movementPenalty: 0,
    speedBonus: 0.5,
    length: 4,
    sequence: false,
    rotate: [-90],
    flip: ['', 'v']
  },
  11: {
    name: 'grassRoadCross',
    sprite: 'grass_road_cross',
    mainType: 'Grass',
    type: ['grass-road'],
    walkable: true,
    movementPenalty: 0,
    speedBonus: 0.5,
    length: 1,
    sequence: false,
    rotate: [0, 90, 180, -90],
    flip: ['', 'v', 'h', 'vh']
  },
  12: {
    name: 'grassRoadEndL',
    sprite: 'grass_road_end',
    mainType: 'Grass',
    type: ['grass-road'],
    walkable: true,
    movementPenalty: 0,
    speedBonus: 0.5,
    length: 1,
    sequence: false,
  },
  13: {
    name: 'grassRoadEndT',
    sprite: 'grass_road_end',
    mainType: 'Grass',
    type: ['grass-road'],
    walkable: true,
    movementPenalty: 0,
    speedBonus: 0.5,
    length: 1,
    sequence: false,
    rotate: [90]
  },
  14: {
    name: 'grassRoadEndR',
    sprite: 'grass_road_end',
    mainType: 'Grass',
    type: ['grass-road'],
    walkable: true,
    movementPenalty: 0,
    speedBonus: 0.5,
    length: 1,
    sequence: false,
    rotate: [180]
  },
  15: {
    name: 'grassRoadEndB',
    sprite: 'grass_road_end',
    mainType: 'Grass',
    type: ['grass-road'],
    walkable: true,
    movementPenalty: 0,
    speedBonus: 0.5,
    length: 1,
    sequence: false,
    rotate: [-90]
  },
  16: {
    name: 'grassRoadStraightT',
    sprite: 'grass_road_straight',
    mainType: 'Grass',
    type: ['grass-road'],
    walkable: true,
    movementPenalty: 0,
    speedBonus: 0.5,
    length: 4,
    sequence: false,
    rotate: [0, 180],
    flip: ['', 'v']
  },
  17: {
    name: 'grassRoadStraightT',
    sprite: 'grass_road_straight',
    mainType: 'Grass',
    type: ['grass-road'],
    walkable: true,
    movementPenalty: 0,
    speedBonus: 0.5,
    length: 4,
    sequence: false,
    rotate: [90, -90],
    flip: ['', 'h']
  },
  18: {
    name: 'grassRocks',
    sprite: 'grass_rocks',
    mainType: 'Grass',
    type: ['grass-rocks'],
    walkable: true,
    movementPenalty: 18,
    speedBonus: 0,
    length: 8,
    sequence: true,
    rotate: [0, 90, 180, -90],
    flip: ['', 'v', 'h', 'vh']
  },
  19: {
    name: 'grassWaterCornerInBR',
    sprite: 'grass_water_corner_in',
    mainType: 'Grass',
    type: ['grass-water'],
    walkable: false,
    length: 2,
    sequence: false,
  },
  20: {
    name: 'grassWaterCornerInBL',
    sprite: 'grass_water_corner_in',
    mainType: 'Grass',
    type: ['grass-water'],
    walkable: false,
    length: 2,
    sequence: false,
    rotate: [90]
  },
  21: {
    name: 'grassWaterCornerInTL',
    sprite: 'grass_water_corner_in',
    mainType: 'Grass',
    type: ['grass-water'],
    walkable: false,
    length: 2,
    sequence: false,
    rotate: [180]
  },
  22: {
    name: 'grassWaterCornerInTR',
    sprite: 'grass_water_corner_in',
    mainType: 'Grass',
    type: ['grass-water'],
    walkable: false,
    length: 2,
    sequence: false,
    rotate: [-90]
  },
  23: {
    name: 'grassWaterCornerOutBR',
    sprite: 'grass_water_corner_out',
    mainType: 'Grass',
    type: ['grass-water'],
    walkable: false,
    length: 2,
    sequence: false,
  },
  24: {
    name: 'grassWaterCornerOutBL',
    sprite: 'grass_water_corner_out',
    mainType: 'Grass',
    type: ['grass-water'],
    walkable: false,
    length: 2,
    sequence: false,
    rotate: [90]
  },
  25: {
    name: 'grassWaterCornerOutTL',
    sprite: 'grass_water_corner_out',
    mainType: 'Grass',
    type: ['grass-water'],
    walkable: false,
    length: 2,
    sequence: false,
    rotate: [180]
  },
  26: {
    name: 'grassWaterCornerOutTR',
    sprite: 'grass_water_corner_out',
    mainType: 'Grass',
    type: ['grass-water'],
    walkable: false,
    length: 2,
    sequence: false,
    rotate: [-90]
  },
  27: {
    name: 'grassWaterPlain',
    sprite: 'grass_water_plain',
    mainType: 'Grass',
    type: ['grass-water'],
    walkable: false,
    length: 1,
    sequence: false,
    rotate: [0, 90, 180, -90],
    flip: ['', 'v', 'h', 'vh']
  },
  28: {
    name: 'grassWaterT',
    sprite: 'grass_water_straight',
    mainType: 'Grass',
    type: ['grass-water'],
    walkable: false,
    length: 2,
    sequence: false,
    flip: ['', 'h']
  },
  29: {
    name: 'grassWaterR',
    sprite: 'grass_water_straight',
    mainType: 'Grass',
    type: ['grass-water'],
    walkable: false,
    length: 2,
    sequence: false,
    rotate: [90],
    flip: ['', 'v']
  },
  30: {
    name: 'grassWaterB',
    sprite: 'grass_water_straight',
    mainType: 'Grass',
    type: ['grass-water'],
    walkable: false,
    length: 2,
    sequence: false,
    rotate: [180],
    flip: ['', 'h']
  },
  31: {
    name: 'grassWaterL',
    sprite: 'grass_water_straight',
    mainType: 'Grass',
    type: ['grass-water'],
    walkable: false,
    length: 2,
    sequence: false,
    rotate: [-90],
    flip: ['', 'v']
  },
};

export default tiles;
